language: csharp
sudo: false
dotnet: 2.1.502
mono:
  - latest
  - 5.10.1
  - 4.6.2
script:
  - git fetch --unshallow
  - dotnet tool install --version "0.31.0" -g Cake.Tool
  - ~/.dotnet/tools/dotnet-cake --target=Travis --configuration=Release
